// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh4VkJwrusliekBAEctVkYorV1NVCWkXc',
    appId: '1:1007535737003:web:a52dc3447be06d01db8fee',
    messagingSenderId: '1007535737003',
    projectId: 'mp-todolist',
    authDomain: 'mp-todolist.firebaseapp.com',
    storageBucket: 'mp-todolist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9NYcNKaKINbVUmEJLYbz8iBwKbcWHb-o',
    appId: '1:1007535737003:android:784748b507f24822db8fee',
    messagingSenderId: '1007535737003',
    projectId: 'mp-todolist',
    storageBucket: 'mp-todolist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrwsTNbXxYdPdXoKhMF2E5rFRHQ_vMjY',
    appId: '1:1007535737003:ios:c82eb628a2d0ab0fdb8fee',
    messagingSenderId: '1007535737003',
    projectId: 'mp-todolist',
    storageBucket: 'mp-todolist.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANrwsTNbXxYdPdXoKhMF2E5rFRHQ_vMjY',
    appId: '1:1007535737003:ios:c82eb628a2d0ab0fdb8fee',
    messagingSenderId: '1007535737003',
    projectId: 'mp-todolist',
    storageBucket: 'mp-todolist.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh4VkJwrusliekBAEctVkYorV1NVCWkXc',
    appId: '1:1007535737003:web:48c5806c95023c56db8fee',
    messagingSenderId: '1007535737003',
    projectId: 'mp-todolist',
    authDomain: 'mp-todolist.firebaseapp.com',
    storageBucket: 'mp-todolist.firebasestorage.app',
  );

}